#!/usr/bin/env ruby
# frozen_string_literal: true

# gen_patterns.rb — reads ext/data_redactor/patterns.c and emits
# patterns_generated.h for use by matcher2.c (88-pattern prototype).
#
# Usage: ruby gen_patterns.rb > patterns_generated.h
# Run from any directory; paths are relative to this script's location.

require "strscan"

EXT = File.expand_path("../../ext/data_redactor", __dir__)

def parse_c_string_array(path, varname)
  src = File.read(path)
  # Find the array body between "varname[...] = {" and the closing "};"
  m = src.match(/#{Regexp.escape(varname)}\[(?:NUM_PATTERNS)?\]\s*=\s*\{(.*?)\};/m)
  raise "#{varname} not found in #{path}" unless m

  body = m[1]
  entries = []
  scanner = StringScanner.new(body)
  until scanner.eos?
    scanner.skip(/\s*/)
    if scanner.scan(%r{/\*.*?\*/}m)
      next
    elsif scanner.scan(/"/)
      str = +""
      until scanner.scan(/"/)
        if scanner.scan(/\\n/)
          str << "\n"
        elsif scanner.scan(/\\t/)
          str << "\t"
        elsif scanner.scan(/\\r/)
          str << "\r"
        elsif scanner.scan(/\\./)
          str << scanner.matched[1]
        else
          str << scanner.scan(/[^"\\]+/).to_s
        end
      end
      scanner.skip(/\s*/)
      # Adjacent string literals
      while scanner.skip(/\s*"/)
        until scanner.scan(/"/)
          if scanner.scan(/\\n/)
            str << "\n"
          elsif scanner.scan(/\\t/)
            str << "\t"
          elsif scanner.scan(/\\r/)
            str << "\r"
          elsif scanner.scan(/\\./)
            str << scanner.matched[1]
          else
            str << scanner.scan(/[^"\\]+/).to_s
          end
        end
        scanner.skip(/\s*/)
      end
      entries << str
    elsif scanner.scan(/NULL/)
      entries << nil
    else
      scanner.scan(/./)
    end
  end
  entries
end

def parse_c_int_array(path, varname)
  src = File.read(path)
  m = src.match(/#{Regexp.escape(varname)}\[(?:NUM_PATTERNS)?\]\s*=\s*\{(.*?)\};/m)
  raise "#{varname} not found in #{path}" unless m
  body = m[1]
  # Strip comments, then extract integers
  body_no_comments = body.gsub(%r{/\*.*?\*/}m, " ")
  body_no_comments.scan(/-?\d+/).map(&:to_i)
end

patterns_c = File.join(EXT, "patterns.c")
names    = parse_c_string_array(patterns_c, "pattern_names")
strings  = parse_c_string_array(patterns_c, "pattern_strings")
prefixes = parse_c_string_array(patterns_c, "pattern_required_literal")
wrapped  = parse_c_int_array(patterns_c, "boundary_wrapped")

n = names.length
raise "array length mismatch" unless [strings, prefixes, wrapped].all? { |a| a.length == n }

def c_str(s)
  return "NULL" if s.nil?
  escaped = s.gsub("\\", "\\\\\\\\").gsub('"', '\\"').gsub("\n", "\\n").gsub("\t", "\\t")
  "\"#{escaped}\""
end

puts "/* patterns_generated.h — auto-generated by gen_patterns.rb. DO NOT EDIT. */"
puts "#ifndef PATTERNS_GENERATED_H"
puts "#define PATTERNS_GENERATED_H"
puts
puts "#define MM88_NUM_PATTERNS #{n}"
puts
# Hand-crafted BM infix literals for always-candidate patterns that have a
# usable required literal somewhere inside the match.  Patterns with no usable
# literal (pure-digit national IDs etc.) get nil = fall back to onig_search.
#
# For variable-offset literals the scan backtracks by max_prefix_len bytes
# before calling onig_match — see matcher5.c Stage 2 logic.
BM_INFIX = {
  "aws_s3_presigned_url"          => "X-Amz-Signature=",  # distinctive, long
  "microsoft_teams_webhook"        => ".webhook.office.com",
  "slack_webhook_url"              => "hooks.slack.com",
  "sentry_dsn"                     => ".ingest.sentry.io",
  "hashicorp_terraform_api_token"  => ".atlasv1.",         # fixed at offset 14
  "uri_with_password"              => "://",
  "bearer_token"                   => "earer ",            # offset 1 from 'B/b'
  "email"                          => "@",
  "uuid_v4"                        => "-4",                # version byte at offset 13
  "phone_e164"                     => "+",                 # must start with +
  "launchdarkly_api_key"           => "-",                 # short but better than nothing
}.freeze

puts "typedef struct {"
puts "    const char *name;"
puts "    const char *regex;         /* POSIX ERE, from patterns.c pattern_strings */"
puts "    const char *prefix;        /* required literal; NULL = always-candidate */"
puts "    int         boundary_wrapped; /* 1 = wrap with (^|[^0-9A-Za-z])(...)([^0-9A-Za-z]|$) */"
puts "    int         prefix_is_infix;  /* 1 = literal is not at regex start; AC fires but regexec scans */"
puts "    const char *bm_literal;    /* BM infix literal for always-candidates; NULL = no filter */"
puts "} mm88_pattern_def_t;"
puts
# Determine which prefixes are infix (not at the start of the regex string after unescaping)
def regex_starts_with_literal?(regex_src, literal)
  regex_plain_start = regex_src.gsub(/\\(.)/, '\1')
  regex_plain_start.start_with?(literal)
end

puts "static const mm88_pattern_def_t MM88_PATTERNS[MM88_NUM_PATTERNS] = {"
n.times do |i|
  comma = i < n - 1 ? "," : ""
  pref = prefixes[i]
  is_infix = pref && !regex_starts_with_literal?(strings[i], pref) ? 1 : 0
  ac_prefix = is_infix == 1 ? nil : pref
  bm = ac_prefix.nil? ? BM_INFIX[names[i]] : nil  # only for always-candidates
  puts "    /* #{i.to_s.rjust(2)}: #{names[i]}#{is_infix == 1 ? " [infix-prefix]" : ""}#{bm ? " [bm:#{bm}]" : ""} */"
  puts "    { #{c_str(names[i])}, #{c_str(strings[i])}, #{c_str(ac_prefix)}, #{wrapped[i]}, #{is_infix}, #{c_str(bm)} }#{comma}"
end
puts "};"
puts
puts "#endif /* PATTERNS_GENERATED_H */"
