/* patterns_generated.h — auto-generated by gen_patterns.rb. DO NOT EDIT. */
#ifndef PATTERNS_GENERATED_H
#define PATTERNS_GENERATED_H

#define MM88_NUM_PATTERNS 88

typedef struct {
    const char *name;
    const char *regex;         /* POSIX ERE, from patterns.c pattern_strings */
    const char *prefix;        /* required literal; NULL = always-candidate */
    int         boundary_wrapped; /* 1 = wrap with (^|[^0-9A-Za-z])(...)([^0-9A-Za-z]|$) */
    int         prefix_is_infix;  /* 1 = literal is not at regex start; AC fires but regexec scans */
} mm88_pattern_def_t;

static const mm88_pattern_def_t MM88_PATTERNS[MM88_NUM_PATTERNS] = {
    /*  0: aws_s3_presigned_url [infix-prefix] */
    { "aws_s3_presigned_url", "https://[a-z0-9.-]+\\.s3\\.amazonaws\\.com/[^[:space:]?]+\\?[^[:space:]]*X-Amz-Signature=[^[:space:]]+", NULL, 0, 1 },
    /*  1: microsoft_teams_webhook [infix-prefix] */
    { "microsoft_teams_webhook", "https://[a-z0-9-]+\\.webhook\\.office\\.com/webhookb2/[a-fA-F0-9-]{36}@[a-fA-F0-9-]{36}/[^/ ]+/[a-fA-F0-9]{32}/[a-fA-F0-9-]{36}", NULL, 0, 1 },
    /*  2: slack_webhook_url [infix-prefix] */
    { "slack_webhook_url", "https://hooks\\.slack\\.com/services/T[A-Z0-9]{8}/B[A-Z0-9]{8}/[A-Za-z0-9]{24}", NULL, 0, 1 },
    /*  3: mongodb_connection_string */
    { "mongodb_connection_string", "mongodb(\\+srv)?://[^[:space:]'\"<>/:@]+:[^[:space:]'\"<>/@]+@[^[:space:]?'\"]+", "mongodb", 0, 0 },
    /*  4: sentry_dsn [infix-prefix] */
    { "sentry_dsn", "https://[a-f0-9]{32}(:[a-f0-9]{32})?@[a-zA-Z0-9.-]+\\.ingest\\.sentry\\.io/[0-9]+", NULL, 0, 1 },
    /*  5: uri_with_password [infix-prefix] */
    { "uri_with_password", "[A-Za-z][A-Za-z0-9+_-]*://[^[:space:]/?#:@]+:[^[:space:]/?#@]+@[A-Za-z0-9.-]+", NULL, 0, 1 },
    /*  6: github_pat_fine_grained */
    { "github_pat_fine_grained", "github_pat_[0-9a-zA-Z_]{82}", "github_pat_", 0, 0 },
    /*  7: jwt */
    { "jwt", "eyJ[A-Za-z0-9_-]{10,}\\.eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]+", "eyJ", 0, 0 },
    /*  8: grafana_api_token */
    { "grafana_api_token", "eyJrIjoi[A-Za-z0-9_=-]{42,}", "eyJrIjoi", 0, 0 },
    /*  9: ssh_public_key */
    { "ssh_public_key", "ssh-(rsa|ed25519|ecdsa) [a-zA-Z0-9/+=]{20,}", "ssh-", 0, 0 },
    /* 10: bearer_token */
    { "bearer_token", "[Bb]earer [a-zA-Z0-9_.=/+:-]{12,}", NULL, 0, 0 },
    /* 11: anthropic_api_key */
    { "anthropic_api_key", "sk-ant-api[0-9]{2}-[A-Za-z0-9_-]{90,}", "sk-ant-api", 0, 0 },
    /* 12: openai_project_api_key */
    { "openai_project_api_key", "sk-proj-[A-Za-z0-9_-]{20,}", "sk-proj-", 0, 0 },
    /* 13: google_api_key */
    { "google_api_key", "AIza[0-9A-Za-z_-]{35}", "AIza", 0, 0 },
    /* 14: aws_access_key_id */
    { "aws_access_key_id", "(A3T[A-Z0-9]|AKIA|ABIA|ACCA|AGPA|AIDA|ANPA|ANVA|APKA|AROA|ASCA|ASIA)[A-Z2-7]{16}", NULL, 0, 0 },
    /* 15: aws_secret_access_key */
    { "aws_secret_access_key", "[A-Za-z0-9/+=]{40}", NULL, 0, 0 },
    /* 16: sendgrid_api_key */
    { "sendgrid_api_key", "SG\\.[a-zA-Z0-9_-]{5,}\\.[a-zA-Z0-9_-]{5,}", "SG.", 0, 0 },
    /* 17: amazon_mws_auth_token */
    { "amazon_mws_auth_token", "amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", "amzn.mws.", 0, 0 },
    /* 18: launchdarkly_api_key */
    { "launchdarkly_api_key", "(api|sdk)-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}", NULL, 0, 0 },
    /* 19: github_classic_pat */
    { "github_classic_pat", "ghp_[0-9a-zA-Z]{36}", "ghp_", 0, 0 },
    /* 20: github_oauth_token */
    { "github_oauth_token", "gho_[0-9a-zA-Z]{36}", "gho_", 0, 0 },
    /* 21: stripe_secret_key */
    { "stripe_secret_key", "sk_live_[0-9a-zA-Z]{24}", "sk_live_", 0, 0 },
    /* 22: clickup_api_key */
    { "clickup_api_key", "pk_[0-9]{6,8}_[A-Z0-9]{32}", "pk_", 0, 0 },
    /* 23: gitlab_pat */
    { "gitlab_pat", "glpat-[0-9a-zA-Z_-]{20}", "glpat-", 0, 0 },
    /* 24: digitalocean_pat */
    { "digitalocean_pat", "dop_v1_[a-f0-9]{64}", "dop_v1_", 0, 0 },
    /* 25: databricks_api_token */
    { "databricks_api_token", "dapi[a-f0-9]{32}", "dapi", 0, 0 },
    /* 26: scaleway_access_key */
    { "scaleway_access_key", "SCW[A-Z0-9]{17}", "SCW", 0, 0 },
    /* 27: pem_private_key */
    { "pem_private_key", "-----BEGIN [A-Z ]*PRIVATE KEY-----", "-----BEGIN ", 0, 0 },
    /* 28: gpg_private_key */
    { "gpg_private_key", "-----BEGIN PGP PRIVATE KEY BLOCK-----", "-----BEGIN PGP PRIVATE KEY BLOCK-----", 0, 0 },
    /* 29: hashicorp_vault_service_token */
    { "hashicorp_vault_service_token", "hvs\\.[A-Za-z0-9_-]{90,120}", "hvs.", 0, 0 },
    /* 30: hashicorp_vault_batch_token */
    { "hashicorp_vault_batch_token", "hvb\\.[A-Za-z0-9_-]{138,300}", "hvb.", 0, 0 },
    /* 31: hashicorp_terraform_api_token [infix-prefix] */
    { "hashicorp_terraform_api_token", "[A-Za-z0-9]{14}\\.atlasv1\\.[A-Za-z0-9_=-]{60,70}", NULL, 0, 1 },
    /* 32: iban_hu */
    { "iban_hu", "HU[0-9]{2}[0-9]{24}", "HU", 0, 0 },
    /* 33: iban_pl */
    { "iban_pl", "PL[0-9]{2}[0-9]{24}", "PL", 0, 0 },
    /* 34: iban_fr */
    { "iban_fr", "FR[0-9]{2}[0-9]{10}[A-Z0-9]{11}[0-9]{2}", "FR", 0, 0 },
    /* 35: iban_it */
    { "iban_it", "IT[0-9]{2}[A-Z][0-9]{10}[A-Z0-9]{12}", "IT", 0, 0 },
    /* 36: iban_pt */
    { "iban_pt", "PT[0-9]{2}[0-9]{21}", "PT", 0, 0 },
    /* 37: iban_es */
    { "iban_es", "ES[0-9]{2}[0-9]{20}", "ES", 0, 0 },
    /* 38: iban_cz */
    { "iban_cz", "CZ[0-9]{2}[0-9]{20}", "CZ", 0, 0 },
    /* 39: iban_ro */
    { "iban_ro", "RO[0-9]{2}[A-Z]{4}[A-Z0-9]{16}", "RO", 0, 0 },
    /* 40: iban_se */
    { "iban_se", "SE[0-9]{2}[0-9]{20}", "SE", 0, 0 },
    /* 41: iban_de */
    { "iban_de", "DE[0-9]{2}[0-9]{18}", "DE", 0, 0 },
    /* 42: iban_ie */
    { "iban_ie", "IE[0-9]{2}[A-Z]{4}[0-9]{14}", "IE", 0, 0 },
    /* 43: iban_ch */
    { "iban_ch", "CH[0-9]{2}[0-9]{5}[A-Z0-9]{12}", "CH", 0, 0 },
    /* 44: iban_at */
    { "iban_at", "AT[0-9]{2}[0-9]{16}", "AT", 0, 0 },
    /* 45: iban_nl */
    { "iban_nl", "NL[0-9]{2}[A-Z]{4}[0-9]{10}", "NL", 0, 0 },
    /* 46: iban_dk */
    { "iban_dk", "DK[0-9]{2}[0-9]{14}", "DK", 0, 0 },
    /* 47: iban_fi */
    { "iban_fi", "FI[0-9]{2}[0-9]{14}", "FI", 0, 0 },
    /* 48: iban_be */
    { "iban_be", "BE[0-9]{2}[0-9]{12}", "BE", 0, 0 },
    /* 49: iban_no */
    { "iban_no", "NO[0-9]{2}[0-9]{11}", "NO", 0, 0 },
    /* 50: email [infix-prefix] */
    { "email", "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}", NULL, 0, 1 },
    /* 51: phone_e164 */
    { "phone_e164", "\\+[0-9]{1,3}[- ]?[0-9][0-9 -]{6,13}[0-9]", NULL, 0, 0 },
    /* 52: brazilian_cnpj */
    { "brazilian_cnpj", "[0-9]{2}\\.[0-9]{3}\\.[0-9]{3}/[0-9]{4}-[0-9]{2}", NULL, 0, 0 },
    /* 53: brazilian_cpf */
    { "brazilian_cpf", "[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}-[0-9]{2}", NULL, 0, 0 },
    /* 54: uuid_v4 */
    { "uuid_v4", "[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}", NULL, 0, 0 },
    /* 55: ipv4 */
    { "ipv4", "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)", NULL, 0, 0 },
    /* 56: credit_card */
    { "credit_card", "(4[0-9]{15}|4[0-9]{12}|5[1-5][0-9]{14}|6011[0-9]{12}|65[0-9]{14}|3[47][0-9]{13}|3[068][0-9]{11}|35[0-9]{14})", NULL, 0, 0 },
    /* 57: indian_aadhaar */
    { "indian_aadhaar", "[0-9]{4}[- ][0-9]{4}[- ][0-9]{4}", NULL, 0, 0 },
    /* 58: mexican_curp */
    { "mexican_curp", "[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[A-Z0-9][0-9]", NULL, 0, 0 },
    /* 59: italian_cf_omocodia */
    { "italian_cf_omocodia", "[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]", NULL, 0, 0 },
    /* 60: italian_cf */
    { "italian_cf", "[A-Z]{6}[0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{3}[A-Z]", NULL, 0, 0 },
    /* 61: uk_nin */
    { "uk_nin", "[A-Z]{2} ?[0-9]{2} ?[0-9]{2} ?[0-9]{2} ?[A-D]", NULL, 0, 0 },
    /* 62: spanish_nie */
    { "spanish_nie", "[XYZ][0-9]{7}[A-Z]", NULL, 0, 0 },
    /* 63: passport_letter_prefix */
    { "passport_letter_prefix", "[A-Z]{1,2}[0-9]{6,7}", NULL, 0, 0 },
    /* 64: korean_rrn */
    { "korean_rrn", "[0-9]{6}-[0-9]{7}", NULL, 1, 0 },
    /* 65: swiss_ahv */
    { "swiss_ahv", "756\\.[0-9]{4}\\.[0-9]{4}\\.[0-9]{2}", "756.", 1, 0 },
    /* 66: finnish_hetu */
    { "finnish_hetu", "[0-9]{6}[-+A][0-9]{3}[0-9A-Y]", NULL, 1, 0 },
    /* 67: swedish_personnummer */
    { "swedish_personnummer", "[0-9]{6}[-+][0-9]{4}", NULL, 1, 0 },
    /* 68: danish_cpr */
    { "danish_cpr", "[0-9]{6}-[0-9]{4}", NULL, 1, 0 },
    /* 69: czech_rodne_cislo */
    { "czech_rodne_cislo", "[0-9]{6}/?[0-9]{3,4}", NULL, 1, 0 },
    /* 70: us_ssn */
    { "us_ssn", "[0-9]{3}-[0-9]{2}-[0-9]{4}", NULL, 1, 0 },
    /* 71: us_itin */
    { "us_itin", "9[0-9]{2}-[0-9]{2}-[0-9]{4}", NULL, 1, 0 },
    /* 72: canadian_sin */
    { "canadian_sin", "[0-9]{3}-[0-9]{3}-[0-9]{3}", NULL, 1, 0 },
    /* 73: australian_tfn */
    { "australian_tfn", "[0-9]{3}[- ][0-9]{3}[- ][0-9]{3}", NULL, 1, 0 },
    /* 74: indian_pan */
    { "indian_pan", "[A-Z]{5}[0-9]{4}[A-Z]", NULL, 1, 0 },
    /* 75: spanish_dni */
    { "spanish_dni", "[0-9]{8}[A-Z]", NULL, 1, 0 },
    /* 76: hungarian_tax_id */
    { "hungarian_tax_id", "8[0-9]{9}", NULL, 1, 0 },
    /* 77: french_nir */
    { "french_nir", "[12][0-9]{2}[01][0-9][0-9]{2}[0-9]{3}[0-9]{3}[0-9]{2}", NULL, 1, 0 },
    /* 78: south_african_id */
    { "south_african_id", "[0-9]{13}", NULL, 1, 0 },
    /* 79: romanian_cnp */
    { "romanian_cnp", "[1-8][0-9]{12}", NULL, 1, 0 },
    /* 80: japanese_my_number */
    { "japanese_my_number", "[0-9]{12}", NULL, 1, 0 },
    /* 81: polish_pesel */
    { "polish_pesel", "[0-9]{11}", NULL, 1, 0 },
    /* 82: belgian_national_number */
    { "belgian_national_number", "[0-9]{11}", NULL, 1, 0 },
    /* 83: norwegian_fodselsnummer */
    { "norwegian_fodselsnummer", "[0-9]{11}", NULL, 1, 0 },
    /* 84: passport_9digits */
    { "passport_9digits", "[0-9]{9}", NULL, 1, 0 },
    /* 85: dutch_bsn */
    { "dutch_bsn", "[0-9]{8,9}", NULL, 1, 0 },
    /* 86: austrian_abgabenkontonummer */
    { "austrian_abgabenkontonummer", "[0-9]{9}", NULL, 1, 0 },
    /* 87: polish_pesel_2 */
    { "polish_pesel_2", "[0-9]{11}", NULL, 1, 0 }
};

#endif /* PATTERNS_GENERATED_H */
