#!/usr/bin/env python3
"""
gen_profile_table.py — booktabs LaTeX table of the §5.1 instruction attribution.

Reads paper/data/profile_summary.csv (engine,category,ir,pct), produced by the
prototypes' profile_engines.sh / profile_categorize.py, and writes
paper/data/profile_table.tex — \input-ed by main.tex inside a \table float.

Each cell is the percent of instructions retired (Callgrind Ir) the engine spends
in that mechanism on the shared ~1 MB payload. Mirrors plot_density_sweep.py's
output style (generated header, raw tabular, booktabs rules).

Usage: python3 gen_profile_table.py
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")

# Display order + human labels for the columns.
COLS = [
    ("automaton", "automaton eval."),
    ("setup", "per-call setup"),
    ("prefilter", "literal pre-filter"),
    ("alloc", "allocation"),
    ("output", "match copy-out"),
    ("other", "other"),
]
# Engines as rows, with display names and a per-engine note column.
ENGINES = [
    ("glibc", "glibc \\texttt{regexec}"),
    ("onigmo", "Onigmo"),
    ("v19", "v19 lazy DFA"),
]


def load():
    pct = {}  # pct[engine][category]
    for r in csv.DictReader(open(os.path.join(DATA_DIR, "profile_summary.csv"))):
        pct.setdefault(r["engine"], {})[r["category"]] = float(r["pct"])
    return pct


def fmt(v):
    if v is None:
        return "---"
    if v < 0.05:
        return "$<$0.1"
    return f"{v:.1f}"


def main():
    pct = load()

    out = []
    out.append("% generated by paper/gen_profile_table.py --- do not hand-edit")
    out.append("\\begin{tabular}{l" + "r" * len(COLS) + "}")
    out.append("\\toprule")
    header = "engine & " + " & ".join(f"{label}" for _, label in COLS) + " \\\\"
    out.append(header)
    out.append("\\midrule")

    for eng_key, eng_label in ENGINES:
        row_vals = pct.get(eng_key, {})
        cells = []
        for cat_key, _ in COLS:
            v = row_vals.get(cat_key)
            # Onigmo's automaton/pre-filter live inside a stripped library; fold its
            # libonig bucket into "automaton eval." and mark the pre-filter cell as
            # not separable, so the table never overclaims an attribution we lack.
            if eng_key == "onigmo" and cat_key == "automaton":
                v = (row_vals.get("automaton", 0.0) + row_vals.get("libonig", 0.0))
                cells.append(fmt(v) + "$^{\\dagger}$")
                continue
            if eng_key == "onigmo" and cat_key == "prefilter":
                cells.append("---$^{\\dagger}$")
                continue
            cells.append(fmt(v if v is not None else 0.0))
        out.append(f"{eng_label} & " + " & ".join(cells) + " \\\\")

    out.append("\\bottomrule")
    out.append("\\end{tabular}")

    text = "\n".join(out) + "\n"
    path = os.path.join(DATA_DIR, "profile_table.tex")
    with open(path, "w") as f:
        f.write(text)
    print(f"wrote {path}")
    print(text)


if __name__ == "__main__":
    main()
